repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless Apply (Maven)
        entry: mvn -q -ntp spotless:apply
        language: system
        pass_filenames: false
        stages: [commit]

      - id: spotless-check
        name: Spotless Check (Maven)
        entry: mvn -q -ntp spotless:check
        language: system
        pass_filenames: false
        stages: [push]

      - id: unit-tests
        name: Unit Tests (Maven)
        entry: mvn -q -ntp -DskipITs test
        language: system
        pass_filenames: false
        stages: [push]
