services:
  mongo:
    image: mongo:8.0
    container_name: ezclaim-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ezclaim
      MONGO_INITDB_ROOT_PASSWORD: E2ClaimPass
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: ezclaim-minio-dev
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: ezclaim
      MINIO_ROOT_PASSWORD: E2ClaimPass
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "--help"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  minio_data:
