spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    mongodb:
      # Root user authenticates against the admin database
      uri: mongodb://ezclaim:E2ClaimPass@localhost:27017/ezclaim?authSource=admin
  cloud:
    function:
      scan:
        enabled: false
    stream:
      defaultBinder: kafka
      function:
        definition: auditEvents
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      bindings:
        auditEvents-in-0:
          destination: audit.events
          group: ezclaim-audit
          content-type: application/json
        auditEvents-out-0:
          destination: audit.events
          content-type: application/json

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:3001
      - http://127.0.0.1:3001
      - https://ezclaim-web.liuzisen.com
      - https://ezclaim-admin.liuzisen.com
  objectstore:
    # For local dev against S3-compatible (Compose MinIO)
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: ezclaim
    secret-key: E2ClaimPass
    bucket: ezclaim-dev
    path-style: true
    ensure-bucket: true
  security:
    jwt:
      # Dev-only secret; do NOT use in prod
      secret: dev-jwt-secret-32-bytes-minimum-keep-local!
      algorithm: HS256
      ttl: PT12H
